name: Update version tag on test server

on:
    create:
        tags:
            - 'v*'

env:
    SERVICE_NAME: kontur-tg-bot

jobs:
    update-tag-on-server:
        runs-on: self-hosted
        if: github.event.ref_type == 'tag'

        steps:
            -   name: Extract tag name
                run: |
                    # Извлекаем имя тега из ref
                    TAG_NAME=${GITHUB_REF#refs/tags/}
                    echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
                    echo "✅ Обрабатываем тег: $TAG_NAME"

            -   name: Load server configuration
                run: |
                    if [ ! -f "/root/.env.servers" ]; then
                      echo "❌ Файл конфигурации серверов .env.servers не найден!"
                      exit 1
                    fi

                    # Загружаем переменные окружения из .env.servers
                    set -a
                    source /root/.env.servers
                    set +a

                    # Проверяем наличие API конфигурации
                    if [ -z "$KONTUR_RELEASE_TG_BOT_API_URL" ] || [ -z "$KONTUR_INTERSERVER_SECRET_KEY" ]; then
                      echo "❌ API конфигурация не найдена в .env.servers!"
                      echo "   Убедитесь, что есть переменные: KONTUR_RELEASE_TG_BOT_API_URL и KONTUR_INTERSERVER_SECRET_KEY"
                      exit 1
                    fi

                    # Формируем имена переменных для тестового сервера
                    HOST_VAR="STAGE_HOST"
                    PASSWORD_VAR="STAGE_PASSWORD"

                    # Получаем значения переменных
                    eval "SERVER_HOST=\$$HOST_VAR"
                    eval "SERVER_PASSWORD=\$$PASSWORD_VAR"

                    if [ -z "$SERVER_HOST" ] || [ -z "$SERVER_PASSWORD" ]; then
                      echo "❌ Конфигурация stage сервера не найдена!"
                      echo "   Убедитесь, что в .env.servers есть переменные: ${HOST_VAR} и ${PASSWORD_VAR}"
                      exit 1
                    fi

                    # Экспортируем все необходимые переменные
                    echo "KONTUR_RELEASE_TG_BOT_API_URL=$KONTUR_RELEASE_TG_BOT_API_URL" >> $GITHUB_ENV
                    echo "KONTUR_INTERSERVER_SECRET_KEY=$KONTUR_INTERSERVER_SECRET_KEY" >> $GITHUB_ENV
                    echo "SERVER_HOST=$SERVER_HOST" >> $GITHUB_ENV
                    echo "SERVER_PASSWORD=$SERVER_PASSWORD" >> $GITHUB_ENV
                    echo "✅ Конфигурация загружена успешно"
                    echo "✅ API URL: $KONTUR_RELEASE_TG_BOT_API_URL"
                    echo "✅ Stage сервер: $SERVER_HOST"

            -   name: Create release record
                run: |
                    # Создаем запись о релизе в базе данных
                    RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
                      -H "Content-Type: application/json" \
                      -d '{
                        "service_name": "${{ env.SERVICE_NAME }}",
                        "release_version": "${{ env.TAG_NAME }}",
                        "status": "initiated",
                        "initiated_by": "${{ github.actor }}",
                        "github_run_id": "${{ github.run_id }}",
                        "github_action_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                        "github_ref": "${{ github.ref }}",
                        "interserver_secret_key": "${{ env.KONTUR_INTERSERVER_SECRET_KEY }}",
                      }' \
                      "${{ env.KONTUR_RELEASE_TG_BOT_API_URL }}/release")
                    
                    HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
                    BODY=$(echo "$RESPONSE" | head -n -1)
                    
                    if [ "$HTTP_CODE" -ne 201 ]; then
                      echo "❌ Не удалось создать запись о релизе. HTTP код: $HTTP_CODE"
                      echo "Ответ: $BODY"
                      exit 1
                    fi
                    
                    # Извлекаем ID релиза из ответа
                    RELEASE_ID=$(echo "$BODY" | jq -r '.id')
                    echo "RELEASE_ID=$RELEASE_ID" >> $GITHUB_ENV
                    echo "✅ Создана запись о релизе с ID: $RELEASE_ID"

            -   name: Update status to building
                run: |
                    curl -s -X PATCH \
                      -H "Content-Type: application/json" \
                      -d '{
                        "status": "initiated",
                        "interserver_secret_key": "${{ env.KONTUR_INTERSERVER_SECRET_KEY }}",
                      }' \
                      "${{ env.KONTUR_RELEASE_TG_BOT_API_URL }}/release"
                    echo "✅ Статус обновлен на 'building'"

            -   name: Update tag on test server
                id: deploy_step
                run: |
                    # Функция для обновления статуса с ошибкой
                    update_failed_status() {
                        curl -s -X PATCH \
                      -H "Content-Type: application/json" \
                      -d '{
                        "status": "failed",
                        "interserver_secret_key": "${{ env.KONTUR_INTERSERVER_SECRET_KEY }}",
                      }' \
                      "${{ env.KONTUR_RELEASE_TG_BOT_API_URL }}/release"
                    }

                    # Используем sshpass для аутентификации по паролю
                    SSH_OUTPUT=$(sshpass -p "${{ env.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ env.SERVER_HOST }} -p 22 << 'EOF' 2>&1
                    set -e

                    cd kontur/${{ env.SERVICE_NAME }}
                    git fetch origin --tags

                    # Сохраняем текущую ветку/тег для проверки
                    CURRENT_REF=$(git symbolic-ref --short HEAD 2>/dev/null || git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD)
                    echo "🔍 Текущее состояние: $CURRENT_REF"

                    # Проверяем, существует ли тег
                    if ! git tag -l | grep -q "^${{ env.TAG_NAME }}$"; then
                        echo "❌ Тег ${{ env.TAG_NAME }} не найден в репозитории!"
                        exit 1
                    fi

                    # Переключаемся на тег
                    echo "🏷️ Переключаемся на тег ${{ env.TAG_NAME }}"
                    git checkout ${{ env.TAG_NAME }}

                    # Очищаем старые ветки (кроме main/master)
                    echo "🧹 Очищаем старые ветки"
                    git for-each-ref --format='%(refname:short)' refs/heads | grep -v -E "^(main|master)$" | xargs -r git branch -D

                    # Очищаем удаленные ветки
                    git remote prune origin

                    echo "✅ Переключение на тег ${{ env.TAG_NAME }} завершено"

                    cd ../kontur-system

                    export $(cat env/.env.app env/.env.db env/.env.monitoring | xargs)

                    echo "🔨 Начинаем сборку контейнера для тега ${{ env.TAG_NAME }}..."
                    docker compose -f ./docker-compose/app.yaml up -d --build ${{ env.SERVICE_NAME }}

                    check_health() {
                        # Если есть HTTP endpoint
                        if curl -f -s -o /dev/null -w "%{http_code}" http://localhost:8005/api/tg-bot/health | grep -q "200"; then
                            return 0
                        else
                            return 1
                        fi
                    }

                    MAX_ATTEMPTS=3
                    ATTEMPT=1
                    SUCCESS=false

                    sleep 10

                    while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
                        echo "🔍 Проверка health (попытка $ATTEMPT из $MAX_ATTEMPTS)..."

                        if check_health; then
                            echo "✅ Health check пройден!"
                            SUCCESS=true
                            break
                        else
                            echo "⏳ Health check не пройден, ждем..."
                            sleep 15
                        fi

                        ATTEMPT=$((ATTEMPT + 1))
                    done

                    if [ "$SUCCESS" = false ]; then
                        echo "❌ Health check не пройден после $MAX_ATTEMPTS попыток"
                        echo "📋 Логи контейнера:"
                        docker logs --tail 50 ${{ env.SERVICE_NAME }}
                        exit 1
                    fi

                    echo "✅ Тег ${{ env.TAG_NAME }} успешно развернут и приложение работает!"
                    EOF
                    )

                    SSH_EXIT_CODE=$?
                    
                    if [ $SSH_EXIT_CODE -ne 0 ]; then
                        echo "❌ Ошибка при деплое на тестовый сервер:"
                        echo "$SSH_OUTPUT"
                        update_failed_status
                        exit 1
                    fi
                    
                    echo "✅ Деплой завершен успешно"

            -   name: Update status to manual testing
                if: success()
                run: |
                    ccurl -s -X PATCH \
                      -H "Content-Type: application/json" \
                      -d '{
                        "status": "failed",
                        "interserver_secret_key": "${{ env.KONTUR_INTERSERVER_SECRET_KEY }}",
                      }' \
                      "${{ env.KONTUR_RELEASE_TG_BOT_API_URL }}/release"
                    echo "✅ Статус обновлен на 'manual_testing'"

            -   name: Verify deployment
                if: success()
                run: |
                    echo "🎉 Деплой тега ${{ env.TAG_NAME }} завершен успешно"
                    echo "📊 Сервер: ${{ env.SERVER_HOST }}"
                    echo "🏷️ Версия: ${{ env.TAG_NAME }}"
                    echo "🧪 Статус: Готов к ручному тестированию"

            -   name: Handle deployment failure
                if: failure()
                run: |
                    echo "❌ Деплой завершился с ошибкой"
                    echo "📊 Сервер: ${{ env.SERVER_HOST }}"
                    echo "🏷️ Версия: ${{ env.TAG_NAME }}"
                    echo "📋 Проверьте логи выше для подробной информации"