name: Update version tag on test server

on:
    create:
        tags:
            - 'v*'

env:
    SERVICE_NAME: ${{ github.event.repository.name }}
    SYSTEM_REPO: loom-system

jobs:
    update-tag-on-server:
        runs-on: self-hosted
        if: github.event.ref_type == 'tag'

        steps:
            - name: Extract tag name
              run: |
                  TAG_NAME=${GITHUB_REF#refs/tags/}
                  echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
                  echo "::notice title=Tag Processing::Processing tag: $TAG_NAME"

            - name: Load server configuration
              run: |
                  source .github/scripts/on-create-version-tag/load_config.sh
                  load_server_config

            - name: Create release record
              run: |
                  source .github/scripts/on-create-version-tag/release_tg_bot_api.sh
                  create_release_record

            - name: Update status to building
              run: |
                  source .github/scripts/on-create-version-tag/release_tg_bot_api.sh
                  update_release_status "building"

            - name: Refresh database
              run: |
                  source .github/scripts/on-create-version-tag/refresh_db.sh
                  refresh_all_databases

            - name: Deploy to test server
              id: deploy_step
              run: |
                  source .github/scripts/on-create-version-tag/deploy.sh
                  deploy_to_server

            - name: Deploy to test server
              id: rollback_test_step
              run: |
                  source .github/scripts/on-create-version-tag/rollback.sh
                  deploy_to_server

            - name: Update status on failure
              if: failure()
              run: |
                  source .github/scripts/on-create-version-tag/release_tg_bot_api.sh
                  update_release_status "staging_failed"

            - name: Update status to manual testing
              if: success()
              run: |
                  source .github/scripts/on-create-version-tag/release_tg_bot_api.sh
                  update_release_status "manual_testing"

            - name: Verify deployment
              if: success()
              run: |
                  source .github/scripts/on-create-version-tag/deploy.sh
                  verify_deployment_success

            - name: Handle deployment failure
              if: failure()
              run: |
                  source .github/scripts/on-create-version-tag/deploy.sh
                  handle_deployment_failure